<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>biteshare-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Stripe.net" Version="46.1.1" />
    <PackageReference Include="QuestPDF" Version="2024.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiteShare.Shared\BiteShare.Shared.csproj" />
    <ProjectReference Include="..\BiteShare.Data\BiteShare.Data.csproj" />
  </ItemGroup>

</Project>
