using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BiteShare.Api.Services;

public class ReceiptPdfService : IReceiptPdfService
{
    public byte[] GenerateItemizedReceipt(
        string sessionName,
        DateTime submittedAtUtc,
        decimal subtotal,
        decimal tax,
        decimal tip,
        decimal deliveryFee,
        IReadOnlyList<ReceiptPdfLine> lines)
    {
        var total = subtotal + tax + tip + deliveryFee;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text("BiteShare Receipt").FontSize(18).Bold();
                    col.Item().Text(sessionName).FontSize(13);
                    col.Item().Text($"Submitted {submittedAtUtc:g} UTC").FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(15).Column(col =>
                {
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn(1);
                            columns.RelativeColumn(1);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Participant").Bold();
                            header.Cell().AlignRight().Text("Owed").Bold();
                            header.Cell().AlignRight().Text("Paid").Bold();
                        });

                        foreach (var line in lines)
                        {
                            table.Cell().Text(line.ParticipantName);
                            table.Cell().AlignRight().Text($"${line.AmountOwed:0.00}");
                            table.Cell().AlignRight().Text(line.PaymentCaptured ? "Yes" : "Pending");
                        }
                    });

                    col.Item().PaddingTop(15).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().PaddingTop(10).Column(summary =>
                    {
                        summary.Item().Row(r => { r.RelativeItem().Text("Subtotal"); r.ConstantItem(80).AlignRight().Text($"${subtotal:0.00}"); });
                        summary.Item().Row(r => { r.RelativeItem().Text("Tax"); r.ConstantItem(80).AlignRight().Text($"${tax:0.00}"); });
                        summary.Item().Row(r => { r.RelativeItem().Text("Tip"); r.ConstantItem(80).AlignRight().Text($"${tip:0.00}"); });
                        summary.Item().Row(r => { r.RelativeItem().Text("Delivery fee"); r.ConstantItem(80).AlignRight().Text($"${deliveryFee:0.00}"); });
                        summary.Item().PaddingTop(5).Row(r =>
                        {
                            r.RelativeItem().Text("Total").Bold();
                            r.ConstantItem(80).AlignRight().Text($"${total:0.00}").Bold();
                        });
                    });
                });

                page.Footer().AlignCenter().Text("Generated by BiteShare").FontSize(8).FontColor(Colors.Grey.Darken1);
            });
        });

        return document.GeneratePdf();
    }
}
